# Generated by Django 5.2.5 on 2025-09-27 16:34

from django.db import migrations

def create_initial_roles(apps, schema_editor):
    Role = apps.get_model('blog', 'Role')

    Role.objects.get_or_create(
        id = 1,
        name = 'default',
        defaults = {'description' : 'Usuário padrão'}
    )

    Role.objects.get_or_create(
        id = 2,
        name = 'admin',
        defaults = {'description' : 'Administrador do sistema'}
    )

def reverse_initial_roles(apps, schema_editor):
    Role = apps.get_model('blog', 'Role')
    Role.objects.filter(name__in=['default', 'admin']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, reverse_initial_roles),
    ]
