# Generated by Django 5.2.5 on 2025-09-27 16:42

from django.db import migrations
from django.conf import settings

ADMIN_ROLE_ID = 2 

def create_admin_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    if not User.objects.filter(username = 'admin').exists():
        user = User.objects.create_superuser(
            username = 'admin',
            password = 'admin'
        )
        user.role = ADMIN_ROLE_ID
        user.save()

def reverse_create_admin_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    User.objects.filter(username = 'admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_create_initial_roles'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
